jobs:

######################### NATIVE WAR CI/CD JOBS #########################

# runCI job that builds and pushes artifact to S3
  - name: docker-multi-container-runcli-elasticbeanstalk_runCI
    type: runCI
    steps:
      - OUT: docker_multi_container_eb_img

# runCLI job that deploys image in ECR to Elastic Beanstalk - TEST
  - name: docker_multi_container_eb_test_deploy
    type: runCLI
    steps:
      - IN: docker_multi_container_eb_img
      - IN: docker_multi_container_eb_awscli
      - IN: docker_multi_container_eb_gitrepo
        switch: off
      - IN: docker_multi_container_eb_params
      - IN: docker_multi_container_eb_params_test
      - TASK:
        # assign Shippable-injected variables to variables used in templates
        - script: export ENVIRONMENT=$DEMO_JAVA_ECR_PARAMS_TEST_PARAMS_ENVIRONMENT PORT=$DEMO_JAVA_ECR_PARAMS_PARAMS_PORT IMAGE_REPO=$DEMO_JAVA_ECR_IMG_SOURCENAME IMAGE_TAG=$DEMO_JAVA_ECR_IMG_VERSIONNAME
        # update template files with values in env variables
        - script: cd $DEMO_JAVA_ECR_GITREPO_STATE/deploy
        - script: pwd
        - script: echo "updating templates with environment variables"
        - script: shippable_replace Dockerrun.aws.json .ebextensions/environmentvariables.config
        # initialize eb cli for app docker_multi_container_eb
        - script: echo "initializing EB"
        - script: eb init docker_multi_container_eb --platform docker-1.12.6 --region us-east-1 --keyname kp-us-east-1
        # deploy latest image to elastic beanstalk
        - script: echo "Deploying new version to Elastic Beanstalk"
        - script: eb deploy $DEMO_JAVA_ECR_PARAMS_TEST_PARAMS_AWS_EB_ENVIRONMENT
        # save latest deployment to state
        - script: echo -e "IMAGE_REPO=$IMAGE_REPO\nIMAGE_TAG=$IMAGE_TAG" >> $DEMO_JAVA_ECR_TEST_DEPLOY_STATE/latest_test_deploy.env

# # runCLI job that deploys image in ECR to Elastic Beanstalk
# # based on previous deployment to TEST environment
#   - name: docker_multi_container_eb_prod_deploy
#     type: runCLI
#     steps:
#       - IN: docker_multi_container_eb_test_deploy
#         switch: off
#       - IN: docker_multi_container_eb_gitrepo
#         switch: off
#       - IN: docker_multi_container_eb_awscli
#       - IN: docker_multi_container_eb_params
#       - IN: docker_multi_container_eb_params_prod
#       - TASK:
#         # load last build version deployed to test from incoming state file
#         - script: source $DEMO_JAVA_ECR_TEST_DEPLOY_STATE/latest_test_deploy.env
#         # assign Shippable-injected variables to variables used in templates
#         - script: export ENVIRONMENT=$DEMO_JAVA_ECR_PARAMS_PROD_PARAMS_ENVIRONMENT PORT=$DEMO_JAVA_ECR_PARAMS_PARAMS_PORT
#         # update template files with values in env variables
#         - script: cd $DEMO_JAVA_ECR_GITREPO_STATE/deploy
#         - script: echo "updating templates with environment variables"
#         - script: shippable_replace Dockerrun.aws.json .ebextensions/environmentvariables.config
#         # initialize eb cli for app docker_multi_container_eb
#         - script: echo "initializing EB"
#         - script: eb init docker_multi_container_eb --platform docker-1.12.6 --region us-east-1 --keyname kp-us-east-1
#         # deploy latest image to elastic beanstalk
#         - script: echo "Deploying new version to Elastic Beanstalk"
#         - script: eb deploy $DEMO_JAVA_ECR_PARAMS_PROD_PARAMS_AWS_EB_ENVIRONMENT
#
