jobs:

######################### NATIVE WAR CI/CD JOBS #########################

# runCI job that builds and pushes artifact to S3
  - name: eb-docker-multi-container_runCI
    type: runCI
    steps:
      - OUT: eb_docker_multi_container_img

# runCLI job that deploys image in ECR to Elastic Beanstalk - TEST
  - name: eb_docker_multi_container_test_deploy
    type: runCLI
    steps:
      - IN: eb_docker_multi_container_img
      - IN: eb_docker_multi_container_awscli
      - IN: eb_docker_multi_container_gitrepo
        switch: off
      - IN: eb_docker_multi_container_params
      - IN: eb_docker_multi_container_params_test
      - TASK:
        # assign Shippable-injected variables to variables used in templates
        - script: >
          export 
          IMAGE_REPO_NODE=$DOCKER_MULTI_CONTAINER_EB_IMG_NODE_SOURCENAME 
          IMAGE_TAG_NODE=$DOCKER_MULTI_CONTAINER_EB_IMG_NODE_VERSIONNAME
          IMAGE_REPO_TOMCAT=$DOCKER_MULTI_CONTAINER_EB_IMG_TOMCAT_SOURCENAME 
          IMAGE_TAG_TOMCAT=$DOCKER_MULTI_CONTAINER_EB_IMG_TOMCAT_VERSIONNAME
          ENVIRONMENT=$DOCKER_MULTI_CONTAINER_EB_PARAMS_TEST_PARAMS_ENVIRONMENT 
          PORT_NODE=$DOCKER_MULTI_CONTAINER_EB_PARAMS_PORT_NODE
          PORT_TOMCAT=$DOCKER_MULTI_CONTAINER_EB_PARAMS_PORT_TOMCAT
        # update template files with values in env variables
        - script: cd $DOCKER_MULTI_CONTAINER_EB_GITREPO_STATE/deploy
        - script: pwd
        - script: echo "updating templates with environment variables"
        - script: shippable_replace Dockerrun.aws.json .ebextensions/environmentvariables.config
        # initialize eb cli for app eb_docker_multi_container_eb
        - script: echo "initializing EB"
        - script: eb init eb_docker_multi_container_eb --platform docker-1.12.6 --region us-east-1 --keyname kp-us-east-1
        # deploy latest image to elastic beanstalk
        - script: echo "Deploying new version to Elastic Beanstalk"
        - script: eb deploy $DOCKER_MULTI_CONTAINER_EB_PARAMS_TEST_PARAMS_AWS_EB_ENVIRONMENT
        # save latest deployment to state
        - script: echo -e "IMAGE_REPO=$IMAGE_REPO\nIMAGE_TAG=$IMAGE_TAG" >> $DOCKER_MULTI_CONTAINER_EB_TEST_DEPLOY_STATE/latest_test_deploy.env

# # runCLI job that deploys image in ECR to Elastic Beanstalk
# # based on previous deployment to TEST environment
#   - name: eb_docker_multi_container_prod_deploy
#     type: runCLI
#     steps:
#       - IN: eb_docker_multi_container_test_deploy
#         switch: off
#       - IN: eb_docker_multi_container_gitrepo
#         switch: off
#       - IN: eb_docker_multi_container_awscli
#       - IN: eb_docker_multi_container_params
#       - IN: eb_docker_multi_container_params_prod
#       - TASK:
#         # load last build version deployed to test from incoming state file
#         - script: source $DOCKER_MULTI_CONTAINER_EB_TEST_DEPLOY_STATE/latest_test_deploy.env
#         # assign Shippable-injected variables to variables used in templates
#         - script: export ENVIRONMENT=$DOCKER_MULTI_CONTAINER_EB_PARAMS_PROD_PARAMS_ENVIRONMENT PORT=$DOCKER_MULTI_CONTAINER_EB_PARAMS_PARAMS_PORT
#         # update template files with values in env variables
#         - script: cd $DOCKER_MULTI_CONTAINER_EB_GITREPO_STATE/deploy
#         - script: echo "updating templates with environment variables"
#         - script: shippable_replace Dockerrun.aws.json .ebextensions/environmentvariables.config
#         # initialize eb cli for app eb_docker_multi_container_eb
#         - script: echo "initializing EB"
#         - script: eb init eb_docker_multi_container_eb --platform docker-1.12.6 --region us-east-1 --keyname kp-us-east-1
#         # deploy latest image to elastic beanstalk
#         - script: echo "Deploying new version to Elastic Beanstalk"
#         - script: eb deploy $DOCKER_MULTI_CONTAINER_EB_PARAMS_PROD_PARAMS_AWS_EB_ENVIRONMENT
#
